### ISSUE TITLE
Gen-Payload creating invalid Tracer strings - websocket 

### ISSUE THREAD

**Issue by robertmd** [nccgroup/tracy#10]
When you create a payload on the websocket version it creates an invalid payload and then the payload seems to never be matched.

![image](https://user-images.githubusercontent.com/2561290/40273639-c28caf20-5b78-11e8-8ae7-992b78c78e40.png)

**Comment by robertmd** [comment]
refreshing fixed the payloads but it still does not match

**Comment by robertmd** [comment]
It seems to have something to do with the XSS game. It seems to be creating errors.

**Comment by jacobheath** [comment]
Fixed in 613c9c45f011bde507053c07b0adcddc5f2147b3
