### ISSUE TITLE
GUID Authz and Project Revamp

### ISSUE THREAD

**Issue by jacobheath** [nccgroup/tracy#101]
- [x] Add GUIDs to all requests from the extension. Should be in the Hoot header
- [x] Add option in settings to add GUID to project
- [x] Add column to tracers table for GUID. Tracers will be associated withsomeone's GUID
- [x] All lookups from the UI should be based on the tracer. Modify to do a whereby with GUID value
- [x] The "admin view" will just be able to know all the GUIDs on a team and query for them all
- [x] Change project API to be generating a GUID
- [x] Add middleware component so that GUIDs are valid before hitting database

**Comment by jacobheath** [comment]
I am actually generating a GUID in the extension now. I didn't think it needed to be an API call

**Comment by jacobheath** [comment]
need to modify the events APIs so that the tracer ID is looked by UUID

**Comment by jacobheath** [comment]
had to guid to requests so that we can modify only the ones that you are suppose to have access to

**Comment by heathj** [comment]
Closed by 7c7413dec0d2465758d3883e6c704592c5ac06bc
