### ISSUE TITLE
Potentially improper handling of multiple Set-Cookie in HTTP response

### ISSUE THREAD

**Issue by knodesec** [nccgroup/tracy#104]
Using tracy-windows-4.0-amd64.exe.zip , I did look at the commits since release but couldn't see anything referencing HTTP response handling, HTTP headers, or cookies.

I've used Tracy for a few engagements and am just doing some training for new colleagues at work. I've set up DVWA and Tracy to show an example of injecting XSS indicators and tracking them in the Tracy framework. DVWA has a security level which is controlled by the "security" cookie, and a session ID "PHPSESSID".

I noticed that routing through Tracy, I cannot change the security level of the application from Low, Medium, High, or Impossible.

Having a look at Wireshark, I can see the following:
```
46	120.511468	192.168.X.X	192.168.X.Y	HTTP	132	POST /DVWA/security.php HTTP/1.1  (application/x-www-form-urlencoded)
[...]
HTML Form URL Encoded: application/x-www-form-urlencoded
    Form item: "security" = "high"
    Form item: "seclev_submit" = "Submit"
    Form item: "user_token" = "01a328956934173e21b1a4bdba954fdb"
```

and the response:
```
49	120.512861	192.168.X.Y	192.168.X.X	HTTP	485	HTTP/1.1 302 Found 
[...]
Set-Cookie: PHPSESSID=aj7jekt7i7214cv21ptvvp9ej3; path=/\r\n
Set-Cookie: security=high\r\n
```

The response in the browser however is missing the second Set-Cookie for the security level. The following is taken from the Network tab in Developer Tools in Firefox.
```
HTTP/1.1 302 Found
Cache-Control: no-store, no-cache, must-revalidate
Connection: Keep-Alive
Content-Length: 0
Content-Type: text/html; charset=UTF-8
Date: Wed, 15 May 2019 07:02:34 GMT
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Keep-Alive: timeout=5, max=100
Location: /DVWA/security.php
Pragma: no-cache
Server: Apache/2.4.29 (Ubuntu)
Set-Cookie: PHPSESSID=aj7jekt7i7214cv21ptvvp9ej3; path=/
```
If I bypass the Tracy proxy, the HTTP requests to and from the server are identical in Wireshark, and the correct Set-Cookie header is seen in the Firefox network tab, and the security level changes as it should do.

Could this indicate some mis-handling of multiple Set-Cookie headers by Tracy? It seems odd that the Go proxy is not as transparent as to remove headers from the response. Unfortunately I'm in a corporate Windows environment, and so it's difficult to build Tracy from source, I'll spin up a Linux VM and see if I can get any further as time permits.

**Comment by knodesec** [comment]
I've tested this with a minimal http server in Go:

```
package main

import (
        "fmt"
        "time"
        "net/http"
)
func main() {
        http.HandleFunc("/", func (w http.ResponseWriter, r *http.Request) {

                addCookie(w, "test1", "123")
                addCookie(w, "test2", "456")
                fmt.Fprintf(w, "Welcome!")
        })

        http.ListenAndServe(":9999", nil)
}


func addCookie(w http.ResponseWriter, name, value string ) {

        expire := time.Now().AddDate(0, 0, 1)
        cookie := http.Cookie{
                Name: name,
                Value: value,
                Expires: expire,
        }
        http.SetCookie(w, &cookie)
}
```

Response from standard connection to server:
```
HTTP/1.1 200 OK
Set-Cookie: test1=123; Expires=Wed, 15 May 2019 14:39:23 GMT
Set-Cookie: test2=456; Expires=Wed, 15 May 2019 14:39:23 GMT
Date: Tue, 14 May 2019 14:39:23 GMT
Content-Length: 8
Content-Type: text/plain; charset=utf-8
```
Response routed through Tracy:
```
HTTP/1.1 200 OK
Content-Length: 8
Content-Type: text/plain; charset=utf-8
Date: Tue, 14 May 2019 14:37:23 GMT
Set-Cookie: test1=123; Expires=Wed, 15 May 2019 14:37:23 GMT
```

**Comment by mrobertsNCC** [comment]
Thanks for reporting this issue. I can't be leave we never ran into this before.

It looks like at https://github.com/nccgroup/tracy/blob/master/proxy/proxy.go#L690 we only copy the first value out of the key. So, if it's set-cookie only the first set-cookie will be in the header.

**Comment by heathj** [comment]
I think it's because there aren't many http response headers that have duplicates in an http response and I was just being silly. but great catch @knodesec! I'll merge this now. Also, if you need any help with Tracy for your training, let us know and we would be happy to help. Always looking for more adoption.

**Comment by heathj** [comment]
Fixed in 1820a9c

**Comment by heathj** [comment]
@knodesec if you would like me to build you a fresh binary with the new changes, shoot me some contact information and I can get that to you. Otherwise, I push a new release here in a little bit.

**Comment by knodesec** [comment]
I'm OK with waiting for an upcoming release, thanks for the quick response and fix.

**Comment by heathj** [comment]
@knodesec a new release has been pushed. Please check it out and verify that it fixes the issue for you.
