### ISSUE TITLE
zzPLAINzz and zzXSSzz not getting converted

### ISSUE THREAD

**Issue by heathj** [nccgroup/tracy#111]
Google account sign-up flow not triggering. It's a POST request with the zzXSSzz in the body.

**Comment by sohelahmed786** [comment]
I'm too facing same problem.. not able to trigger even a simple xss on demo.testfire.net or xss-game.appspot.com/level1

**Comment by heathj** [comment]
hmm, @sohelahmed786  how are you trying to trigger the flow? I'm curious if it is a related issue or a new one. Here's what I get when I try it:

![image](https://user-images.githubusercontent.com/3597899/66852473-e5d6b400-ef31-11e9-86fd-589254ee5992.png)

![image](https://user-images.githubusercontent.com/3597899/66852489-f0914900-ef31-11e9-81ee-0db2095bd9b4.png)

![image](https://user-images.githubusercontent.com/3597899/66852521-fe46ce80-ef31-11e9-96f1-e4123b5c85ec.png)

which seems to be working as expected.

**Comment by sohelahmed786** [comment]
in my browser it's not working as expected.. don't know why..
  


![tracy](https://user-images.githubusercontent.com/12643717/66853967-12c0b080-ef9e-11e9-9df1-90f6e5611459.png)
![tracy2](https://user-images.githubusercontent.com/12643717/66853971-16ecce00-ef9e-11e9-9bb6-c9ae82052070.png)

**Comment by heathj** [comment]
This might be a silly question, but you clicked the Search button right?

**Comment by sohelahmed786** [comment]
ofcourse i clicked , without it how will it execute my payload... Comparing to your image mine doesn't has url or method name... that means it has some problem maybe because of some configuration in my firefox..

**Comment by sohelahmed786** [comment]
lol it's working on chrome ... what happened to my firefox...

![chrome-tracy](https://user-images.githubusercontent.com/12643717/66856425-cdeb4880-efa2-11e9-94b6-a964f72ff12a.png)

**Comment by heathj** [comment]
Yea that was why I asked if you clicked the submit button. Tracy should catch the HTTP request like it did in my example. Do you have other extensions installed on Firefox? Or an HTTP proxy setup? Maybe they aren't playing well together.

**Comment by sohelahmed786** [comment]
hmm maybe it's becz of firefox version. I'm using 60.8.0esr (64-bit). I tried disabling all addons except tracy... problem persists.

**Comment by heathj** [comment]
I should also mention that this issue was written up because I was having issues with the `hnxgoyqccn` and `\"'<cxzbkixdeh>` payloads, which only get converted when the network requests get triggered. It looks like from your screenshot, you are using the `\"'<nnmlvnctwr>` payloads, which get generated right then and there.

> 
> 
> hmm maybe it's becz of firefox version. I'm using 60.8.0esr (64-bit). I tried disabling all addons except tracy... problem persists.

OOOOO, yea that is an old old Firefox version. You can probably see the errors if you open the dev console in the page and or debug the add-on and open the background page console. You'll need update to get that working.

**Comment by heathj** [comment]
I could probably do a better job making the extension more backward compatible, I think I use some newer APIs that aren't in that version of Firefox, such as `[].flat()` https://caniuse.com/#search=flat

**Comment by heathj** [comment]
👍 sure thing! happy to help

**Comment by jacobheath** [comment]
This issue is caused by the following: "Note that the submit event fires on the <form> element itself, and not on any <button> or <input type="submit"> inside it. (Forms are submitted, not buttons.)

The submit event only fires when the user clicks a submit button (<button> or <input type="submit">) in a form. The event is not raised when calling the form.submit() method directly."

https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/submit_event

**Comment by jacobheath** [comment]
my onsubmit handler isn't being called when javascript is used to submit forms. I will have to force call these or find a way to override form submit functions with a proxy to catch them properly.
