### ISSUE TITLE
No delete project option

### ISSUE THREAD

**Issue by sohelahmed786** [nccgroup/tracy#114]
Well there is a create project option which is very helpful. People will try create a project for every domain i guess. But if there are a lot of domains it'll be difficult to manage those. A delete project option will be alot helpful.

**Comment by heathj** [comment]
Great suggestion, I don't think that would be too difficult to implement. I'll add it to my next round of features to look at.

**Comment by jacobheath** [comment]
Had some time today to review this. The commit above doesn't purge the data, but effectively archives the project so you can't interact with it anymore. If you find that you need to actually purge the data, let me know, but this should be up on the Chrome and Firefox stores pretty soon.
