### ISSUE TITLE
Importing Existing Payloads

### ISSUE THREAD

**Issue by eflores945** [nccgroup/tracy#124]
A feature to import existing payloads into Tracy.

Useful in the event, someone else has already filled the web app with tracers.

**Comment by heathj** [comment]
@eflores945 this is added in the settings page now. If you ever come across a string you want traced, navigate to the settings page and import it as a tracer. It should show up with a type of "IMPORT" and obviously won't have a screenshot, but tracy will look for it in future page renders. 

Thanks for the suggestion! Keep them coming!
