### ISSUE TITLE
hook innerHTML

### ISSUE THREAD

**Issue by jacobheath** [nccgroup/tracy#13]
Since 

~~~html
<!DOCTYPE html>
<html>
<head>
                <title></title>
</head>
<body>
<script>
                var a = document.createElement("div");
                a.innerHTML = "<img src='1' onerror='alert(1)'/>";
</script>
</body>
</html>
~~~

**Comment by jacobheath** [comment]
Currently working on this. Writing a content script that waits for the page to load and hooks all the innerHTML functions.

**Comment by robertmd** [comment]
Why wait for the page to load?

**Comment by jacobheath** [comment]
I am using this code:

~~~js
var originalSet = Object.getOwnPropertyDescriptor(
  Element.prototype,
  "innerHTML"
).set;

Object.defineProperty(Element.prototype, "innerHTML", {
  set: function(value) {
    // change it (ok)
    var new_value = my_function(value);

    //Call the original setter
    return originalSet.call(this, new_value);
  }
});

function my_function(value) {
  console.log("SOMEONE SET INNERHTML", value);
  //Do whatever you want here
  return value + " World!";
}
~~~

It didn't seem to be catching things like jQuery's html() function and I thought that it had something to do with the way I was rendering the content script. It might be that I need to inject into the page for it to hook correctly though. I think what I have tried is just loading it as a content script.

**Comment by robertmd** [comment]
Should we be using the es6 proxy API?

That is strange that jQuery was not triggering. Could it be using something
else?

**Comment by robertmd** [comment]
Ooo.. I miss read. You do need to load it into user land. You can reuse the
injector code.

**Comment by jacobheath** [comment]
If I am not mistaken, Proxy needs to be called on specific object instances. I don't think it works on object prototypes. So if someone was creating an object like with `document.createObject`, it wouldn't trigger when they set innerHTML
