### ISSUE TITLE
TLS certificate error

### ISSUE THREAD

**Issue by HD421** [nccgroup/tracy#17]
[ERROR]:2018/06/14 18:25:48 websocket.go:42: websocket: close 1001 (going away)
[ERROR]:2018/06/14 18:25:56 websocket.go:42: websocket: close 1001 (going away)
[ERROR]:2018/06/14 18:26:33 proxy.go:86: remote error: tls: unknown certificate
[ERROR]:2018/06/14 18:26:36 proxy.go:86: remote error: tls: unknown certificate
[ERROR]:2018/06/14 18:26:39 proxy.go:86: remote error: tls: unknown certificate

Got these errors after downloading new build today. I removed old ~/.tracy directory and certificate, but installation of new one doesn't help.
Also extension is unable to connect to API (I'm using Firefox).

**Comment by jacobheath** [comment]
The websocket error just indicates a websocket connection was closed. It probably shouldn't be an error. Out of curiosity, did you use the plugin from the source repository or did you install from the Firefox app store? Also, when you removed the old certificate, did you also delete the certificate from Firefox's truststore and install the new one?

**Comment by HD421** [comment]
I repeated the whole process again now(reinstall extension, certificate, rebuild server), the problem was solved. Sorry that bothered you.

**Comment by jacobheath** [comment]
No worries at all! I am about to push an update to the extension that might help with this flow. Sometimes the websocket connection gets out of sync and the extension can't connect. Hopefully, this commit will fix that.  Let us know if you've got other issues.
