### ISSUE TITLE
Add a settings pane for UI

### ISSUE THREAD

**Issue by jacobheath** [nccgroup/tracy#19]
Currently, the UI does not have a way to change the settings to something new. For example, if the API server is set to a different port, the UI will not work. Ideally, the UI should pull the settings from the plugin. However, if the plugin is not installed, there might be a textbox that is revealed to change the port number and host for the API.

**Comment by heathj** [comment]
By default, I think this should pull from the extension. In most cases, people will be using the web UI in the same browser the extension is loaded in. However, it doesn't have to work like that. So it should fall back to a input field near the bottom of the page if it can't detect the tracy plugin.

**Comment by heathj** [comment]
Closed in #2c59ae07ef8ecc0885e4842e143571d24d558d76, but still needs some styling. Doesn't look very pretty.
