### ISSUE TITLE
Proxy whitelist hard-coded

### ISSUE THREAD

**Issue by jacobheath** [nccgroup/tracy#27]
The proxy whitelist is hard-coded to the default server configuration and ports. This should change based on the configuration file.

**Comment by heathj** [comment]
I should say it is hardcoded in the configuration file:

https://github.com/nccgroup/tracy/blob/master/configure/default.go#L14

The whitelist should autogenerate these values based on the configuration file and probably shouldn't a configuration option.

**Comment by heathj** [comment]
Closed by efa221480018d53733b3703781ca52382f7691be
