### ISSUE TITLE
Add styling to dropdown menu

### ISSUE THREAD

**Issue by mrobertsNCC** [nccgroup/tracy#3]
The plugin dropdown menu does not look that great. We should think about styling it.

**Comment by heathj** [comment]
@mrobertsNCC got any examples I can pull from for this?

**Comment by robertmd** [comment]
speaking of this. I was thinking it might be a good idea to add a right click menu to. In case it is borked on a box.

**Comment by natnaelg** [comment]
right click menu + fill in all fields would be 👌

**Comment by robertmd** [comment]
Like this?

![image](https://user-images.githubusercontent.com/2561290/43301237-c3c93d4c-9118-11e8-812e-087f8dda94a4.png)

**Comment by heathj** [comment]
Drop shadow and tracy color theme. What else can you ask for?

**Comment by heathj** [comment]
I'm working on the context menu right now. I actually like the colors, but what if we need the charcoal as the background to make it match more of the tracy UI.

**Comment by robertmd** [comment]
Ok, I can try that. I just picked random colors tell it kinda worked.

**Comment by heathj** [comment]
Also, might be good to try and make the font the same.

font-family: Menlo, Monaco, Consolas, "Courier New", monospace; 
font-size: small;

**Comment by robertmd** [comment]
This?

![image](https://user-images.githubusercontent.com/2561290/43352773-9e2b8b10-91dd-11e8-83b7-a377635af9a9.png)

**Comment by heathj** [comment]
Nice. I'm thinking make the font match the UI and adding padding to the borders and cells.

**Comment by robertmd** [comment]
Weird, I thought I applied the font that you gave me.

**Comment by heathj** [comment]
O maybe you did. I looked like the one from before. If so, ignore that comment

**Comment by heathj** [comment]
1082b4b8a0d379f17663701ae9d15b7f02f5d3f6 has the context menus and autofill feature. Autofill should be configured in the plugin preferences page:

![image](https://user-images.githubusercontent.com/3597899/43605977-f36bc1b0-964e-11e8-9745-97d843114c5a.png)

@natnaelg autofill seems to work, but it does make navigating some pages pretty annoying. I probably need yall to user test it out and see if the flow can be better.
