### ISSUE TITLE
Add a Benchmark Framework for Proxy Changes

### ISSUE THREAD

**Issue by natnaelg** [nccgroup/tracy#31]
I'm interested in adding benchmarking for the proxy before I make some memory management changes so that I can actually measure if they're making a significant change. So I'm going to do some research and write benchmarking tests

**Comment by natnaelg** [comment]
Still need to add a tls version

**Comment by heathj** [comment]
I think this can be closed, right? TLS is finished?

**Comment by natnaelg** [comment]
Yep, https://github.com/nccgroup/tracy/pull/40

**Comment by robertmd** [comment]
There That I

**Comment by robertmd** [comment]
E


y it t it u t





😉😗🛃🚹♿


I'd htd rrhudgggz
