### ISSUE TITLE
Add an in memory caching layer in front of sqlite

### ISSUE THREAD

**Issue by natnaelg** [nccgroup/tracy#47]
Most of the cumulative time is spent in gorm. I want to add an lru arc cache(https://github.com/hashicorp/golang-lru/blob/master/arc.go) in front of the DB calls since most of the time is spent in common.GetTracers which will keep those in the cache as they'll be accessed regularly. The problem is that GORM doesn't make doing this caching very easy (https://github.com/jinzhu/gorm/issues/306). I recommend

1. We move to using sqlx directly since the requests that are being made are not that complicated
2. We use an in memory cache with write back (only write to sqlite on cache eviction)

Thoughts @jacobheath @robertmd ?

**Comment by robertmd** [comment]
Funny enough it used to all be SQL but we stopped using it was super annoying to add new stuff to the DB. So Jake moved it over to GORM.

**Comment by heathj** [comment]
I'd really like to avoid moving back to raw queries. It's such a pain when we want to add columns to tables, and we have a lot of new features coming down the pipe that will require that.

**Comment by heathj** [comment]
I'd also say that I don't think the majority of the time is spent on Gorm in a normal usecase of the application. GetTracers is only called when you load the UI on page load. Since we got rid of polling, this shouldn't be considered a most of the cumulative time. It might seem like it in the benchmarks because a lot of the tests first add tracers to the database to initialize it and then retrieve them to make sure they were inserted correctly.

**Comment by natnaelg** [comment]
Every connection calls `common.GetTracers` https://github.com/nccgroup/tracy/blob/master/proxy/proxy.go#L66

**Comment by heathj** [comment]
I'm not super familiar with the advantages of non-relational databases. What would a non-relational database solve here?

**Comment by robertmd** [comment]
Funny enough it used to be a NoSQL DB before it was sqlite. I'm kind of fine with it but the only problem is that it would be annoying for a dev to have to run a redis server locally.

**Comment by heathj** [comment]
@robertmd, by NoSQL do you mean a golang map 😛

**Comment by heathj** [comment]
Also, why are non-relational databases easier to cache?

**Comment by natnaelg** [comment]
Mmk, I'll leave it alone, y'alls project.

I mean it could be just as easy to cache if you didn't use gorm and could cache based on the prepared statement. I'm conflating not using gorm and rdbs

**Comment by robertmd** [comment]
ooo, I just thought of something. I was on board with you Nati but I forgot
about all the data deduping we do. It might be tricky to do that in NoSQL.
If we don't do that data sizes get out of hand super fast.

**Comment by heathj** [comment]
I'm not a super fan of Gorm myself. It's lacking some pretty basic features, so I am all for something that makes tracy better. I just don't know alot about database tradeoffs, so I was asking a lot of questions.
