### ISSUE TITLE
Autofill Right Click

### ISSUE THREAD

**Issue by mrobertsNCC** [nccgroup/tracy#55]
Instead of having the autofill in the settings, how about having it as a right click option?

**Comment by madaratech** [comment]
This would be useful as for now, it don't have the option to fill the `tracy` payload in GET request/URI.

**Comment by madaratech** [comment]
> Do you mean actually adding them to the address bar of the browser?

Yes.

**Comment by heathj** [comment]
Keep in mind, this feature will not add tracer strings to the address bar, only the input fields and editable text areas that tracy normally tracks. I'm not sure about trying to change location attribute of the document. It might mess with the state of the app. Can you give me a usecase where you wouldn't want to use a zzXSSzz or zzPLAINzz payload instead?
