### ISSUE TITLE
cert

### ISSUE THREAD

**Issue by rayenmessaoudi** [nccgroup/tracy#6]
Hi ,
i want to ask where is the certificate file ?

**Comment by mrobertsNCC** [comment]
It should be in the .tracy folder in your home directory. In windows that would C:\Users\<Your User name>/.tracy and in Linux/Macs it would be in ~/.tracy. The file name is cert.pem.

**Comment by jacobheath** [comment]
Also, Tracy needs to run once to generate a certificate. If you still can't find it, let us know, but I am going to close this for now.
