### ISSUE TITLE
Binary not launching on Ubuntu 

### ISSUE THREAD

**Issue by bennyncc** [nccgroup/tracy#71]
Downloaded the binary version 0.5 from the releases, unzipped, chmod, then I try to run I get:

```
./tracy-linux-amd64 
panic: interface conversion: interface {} is nil, not string

goroutine 1 [running]:
github.com/nccgroup/tracy/configure.Setup()
	/ext-go/1/src/github.com/nccgroup/tracy/configure/configure.go:169 +0x902
main.init.0()
	/ext-go/1/src/github.com/nccgroup/tracy/main.go:65 +0x5f
main.init()
	<autogenerated>:1 +0xf6
```

FYI
`uname -a`
`4.15.0-42-generic #45-Ubuntu SMP Thu Nov 15 19:32:57 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by heathj** [comment]
I think this is a configuration file regression. When you delete the file `~/.tracy/tracy.json`, and rerun the binary, do you get the error? We made some changes to the configuration file in this release that don't work well with the old verison.

**Comment by bennyncc** [comment]
Removal of `~/.tracy/tracy.json` fixed the issue for me.
