### ISSUE TITLE
Log Crashes to ~/.tracy

### ISSUE THREAD

**Issue by justinmoore-ncc** [nccgroup/tracy#72]
Hey folks,

First, thanks for developing tracy. It's a great tool that I'm excited to introduce into my workflow.

While using Tracy it hit a fatal error which dumped a huge log to the screen and It was kind of a hassle to copy the error from my tmux buffer into a useable file. Because Tracy also has a directory it uses to store preferences, would it be possible to also log crashes into this directory to improve triaging?

Thanks,
Justin

**Comment by heathj** [comment]
You're right, we should probably add this by default. For logs, we have the `-o` parameter that you can provide and it will write all logs messages to an external file. However, I don't think it catches panics, which is what I imagine you hit.

**Comment by heathj** [comment]
I think I need to just add a recover statement to the main function and write any errors to a file.

**Comment by heathj** [comment]
No long applicable
