### ISSUE TITLE
Performance issues in extension

### ISSUE THREAD

**Issue by heathj** [nccgroup/tracy#78]
When loading large pages, tracy seems to hang the page. Waiting to get more specific information.

**Comment by jacobheath** [comment]
Probably because of the proxy making so many GetTracer callers. Time to optimize this out.

**Comment by heathj** [comment]
I think we can move https://github.com/nccgroup/tracy/blob/master/plugin/scripts/background.js#L140 to the server if we push all DOM events to the binary. The reason we didn't do this from the start was because we were doing everything with HTTP requests and it was a pain to see all those requests going over Burp. Also, there are just a lot of DOM events and it generated a lot of network traffic. However, now we have a websocket connection and could push them one at a time. I would prefer to do this because I don't want users' browsing experience to be negatively impacted by installing the plugin. Doesn't seem to be a huge problem, but for large pages, the search takes a long time.
