### ISSUE TITLE
Use this one little loophole to speed up leaf cert generation - CSPRNGs hate it

### ISSUE THREAD

**Issue by parsiya** [nccgroup/tracy#8]
Code has a comment `Currently, it is taking a lot of time to generate these certificates`. I don't think it's a bottleneck, but if needed we can speed this up by re-using the CA key instead of generating a new key for each certificate in proxy/cert.go:generateCert. CA is already passed to that function anyways.

Sure it's not secure, but if someone accesses our locally stored keys, we have bigger problems.

We can also just generate a second keypair for leaf cert and add it to config during setup. Then re-use that for all leaf certs.

**Comment by jacobheath** [comment]
Do we generate a new key for each certificate? It looks like we sign the generated certificate with the CA cert here: 

https://github.com/nccgroup/tracy/blob/master/proxy/cert.go#L107

In any case, I think you are right; it's probably not a bottleneck and not something that need to be worried about too much.

**Comment by parsiya** [comment]
> Do we generate a new key for each certificate?

Yes, [cert.go#L103](https://github.com/nccgroup/tracy/blob/master/proxy/cert.go#L103).

``` go
// Leaf cert key generated.
priv, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
if err != nil {
	return tls.Certificate{}, KeyPairBytes{}, err
}
derBytes, err := x509.CreateCertificate(rand.Reader, &template, certs[0], priv.Public(), cert.PrivateKey)
if err != nil {
	return tls.Certificate{}, KeyPairBytes{}, err
}
```

Each cert has its own key, then we pass the template and the leaf cert's public key to the function along with CA's cert and private key.

Not a bottleneck, I only made an issue because of the comment in code. Going to close the issue.

**Comment by jacobheath** [comment]
Ah I see what you were saying. Use the private key from `cert`. Yes, we could do that. It's possible tracy might be used on large numbers of sites in the future and this speed up could help. For now, I'll leave it closed and keep in mind when that time comes. Thanks!
