### ISSUE TITLE
UI Updates

### ISSUE THREAD

**Issue by heathj** [nccgroup/tracy#84]
I am currently working on a new UI, but if @bennyncc or @robertmd, @mrobertsNCC  wanted to help, below is a very rough sketch of what I was thinking:

![img_20190211_072818](https://user-images.githubusercontent.com/3597899/52573317-b8e46700-2dce-11e9-9f9d-169a80ee08cb.jpg)

Some more detail:

- The far right box should be the main frame of the application and should be scrollable to fill all the details we need in there. I don't really want every to feel so cramped anymore into a single page
- The far left skinny bar should have buttons on it that navigate to other pages, like settings. These should actually use new pages to avoid making everything so cramped
- The tables are pretty much as they are now, but with less columns
- I started this work in the branch `new-ui`. I've added redux so it looks a lot different.

A couple of things that would be nice to do for this (feel free to claim the tasks)
- [x] Strip out bootstrap
- [x] Strip out unneeded CSS
- [ ] Design UI for reproductions panel. I don't know how this should look yet

**Comment by bennyncc** [comment]
I'll take on the CSS and bootstrap tasks.

**Comment by heathj** [comment]
Sorry @bennyncc already stripped it out. Snooze ya' lose

**Comment by heathj** [comment]
Also, I removed the requirement for reproduction steps. I think I will need to redo that feature entirely so I am excluding it from the new UI.

**Comment by heathj** [comment]
Also, this has been pretty much finished in tracy-ext-only branch.
