### ISSUE TITLE
Add plugin to the tracy folder

### ISSUE THREAD

**Issue by heathj** [nccgroup/tracy#88]
Might be nice to write the plugin of the currently executing tracy binary into the tracy folder for reference. This would make it easy to move back a version. The flow would be: 

- Download the tracy binary
- Run it
- Load the plugin in the tracy folder using the load unpacked extension

The current flow requires the user to also download the git repo and then browse to the commit version and load it.

**Comment by jacobheath** [comment]
Removing this because of how we are moving to the extension.
