### ISSUE TITLE
Tracy standalone browser extension: Tracy UI logs network requests which were not actually made

### ISSUE THREAD

**Issue by gothinski** [nccgroup/tracy#99]
Forms that don't submit requests are getting logged in Tracy as a network request. This is possibly due to multiple 'submit' events where one of them fails a validation check.

For example: In my web app there is a username field which has a validation check via a 'onSubmit'. The validation fails for a 'zzPLAINzz' payload and no network request is made, but Tracy shows a GET request.

**Comment by jacobheath** [comment]
I think that should do it. If you update your plugin with the lastest from that branch, let me know if that doesn't resolve your issue.
